// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_wb-yl_hXtLbcz7FwXMqJ-s2FHW7hwIc',
    appId: '1:74308265195:web:aa785905c950c5fc5a8aae',
    messagingSenderId: '74308265195',
    projectId: 'hrms-6d0e8',
    authDomain: 'hrms-6d0e8.firebaseapp.com',
    storageBucket: 'hrms-6d0e8.firebasestorage.app',
    measurementId: 'G-QMJ3JQNHBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy4R2IAlfwDz20hVGH04N3vS7BZnw-GT8',
    appId: '1:74308265195:android:7869107890934ef35a8aae',
    messagingSenderId: '74308265195',
    projectId: 'hrms-6d0e8',
    storageBucket: 'hrms-6d0e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBfqinXhXdfb2iXzTud7_0c-h7sMoyQuk',
    appId: '1:74308265195:ios:eaca126ca30e7a805a8aae',
    messagingSenderId: '74308265195',
    projectId: 'hrms-6d0e8',
    storageBucket: 'hrms-6d0e8.firebasestorage.app',
    iosClientId: '74308265195-1rkdihv255mdokae3gdot4vbu0frulnn.apps.googleusercontent.com',
    iosBundleId: 'com.mridul.hrms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBfqinXhXdfb2iXzTud7_0c-h7sMoyQuk',
    appId: '1:74308265195:ios:eaca126ca30e7a805a8aae',
    messagingSenderId: '74308265195',
    projectId: 'hrms-6d0e8',
    storageBucket: 'hrms-6d0e8.firebasestorage.app',
    iosClientId: '74308265195-1rkdihv255mdokae3gdot4vbu0frulnn.apps.googleusercontent.com',
    iosBundleId: 'com.mridul.hrms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_wb-yl_hXtLbcz7FwXMqJ-s2FHW7hwIc',
    appId: '1:74308265195:web:102f0f67ec2e0d225a8aae',
    messagingSenderId: '74308265195',
    projectId: 'hrms-6d0e8',
    authDomain: 'hrms-6d0e8.firebaseapp.com',
    storageBucket: 'hrms-6d0e8.firebasestorage.app',
    measurementId: 'G-8KFFMGC390',
  );
}
